name: Docker

on:
  workflow_dispatch:
  push:
    branches:
      - main
    tags:
      - "*"
  pull_request:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - run: make docker/build
      - name: docker login
        if: github.ref == 'refs/heads/develop' || startsWith(github.ref, 'refs/tags/')
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
        run: make docker/login
      - name: docker push
        if: github.ref == 'refs/heads/develop'
        run: make docker/push
      - name: docker push (tag)
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          make docker/tag DOCKER_TAG=${GITHUB_REF#refs/tags/}
          make docker/push
